version: '3'

services:

  # App Service
  goservice1:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "5002:5002" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    environment:
      - port=5002
    depends_on: 
      - mongodb # This service depends on mongodb. Start that first.

  goservice2:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "5003:5003" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    environment:
      - port=5003
    depends_on: 
      - mongodb # This service depends on mongodb. Start that first.

  goservice3:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "5004:5004" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    environment:
      - port=5004
    depends_on: 
      - mongodb # This service depends on mongodb. Start that first.

  # Mongodb Service   
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - ./data:/data/db
  nginx:
    build:
      context: ../gochatui/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - "goservice1"
      - "goservice2"
      - "goservice3"